const typo = {
  display3: {
    fontFamily: 'Pretendard',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 'normal',
  },
  display2: {
    fontFamily: 'Pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  display1: {
    fontFamily: 'Pretendard',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 300,
    lineHeight: 'normal',
  },
  headline2: {
    fontFamily: 'Pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  headline1: {
    fontFamily: 'Pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 'normal',
  },
  subhead2: {
    fontFamily: 'Pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  subhead1: {
    fontFamily: 'Pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 800,
    lineHeight: 'normal',
  },
  body4: {
    fontFamily: 'Pretendard',
    fontSize: '15px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  body3: {
    fontFamily: 'Pretendard',
    fontSize: '15px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    letterSpacing: '0.6px',
  },
  body2: {
    fontFamily: 'Pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  body1: {
    fontFamily: 'Pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
  caption2: {
    fontFamily: 'Pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  caption1: {
    fontFamily: 'Pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
};

export default typo;
